### ISSUE TITLE
Raise Priority of the template from 40 to 1.

### ISSUE THREAD

**Issue by lucianolingnau** [PaperCutSoftware/PRTGTemplateGenerator#3]
Hi There. I'm with Paessler's Tech Support Team.
We appreciate the effort you put into creating this template generator to make the integration with PRTG easier. However, I want to report an issue that has come up in a recent tech support case.

Each template generated by this script comes with **priority="40"**. The Problem is, that this translates to PRTG as built-in/standard device template, as a result any discovery with "Automatic device identification (standard, recommended)" in PRTG deploys the corresponding sensors on any device, not just on the relevant device.

My proposed solution is to update the template to generate templates with priority="1", which PRTG handles as _Custom_ template. Hence it is only applied/used when the template is specifically selected from the list ( Automatic sensor creation using specific device template(s)).

Thanks!

Ps.: Not related to the above and not an issue, but one of the templates created by this script deploys several ptfhttpxmlrestvalue sensors. In case you guys are not aware of it yet, there's a new "Rest Custom" sensor that can monitor multiple XML/JSON nodes via a single sensor. Some examples:

- https://kb.paessler.com/en/topic/75798-rest-custom-sensor-wunderground
- https://kb.paessler.com/en/topic/78049-rest-custom-sensor-example-for-bitcoin-via-coindesk

**Comment by alecthegeek** [comment]
Creating a new issue #5 related to 2nd point raised above
